<div class="container-fluid">

    <div class="row justify-content-center">
        <div class="col-sm-8">

            <div class="card mt-5">
                <div class="card-body clickable" onclick="openModel()">
                    <h5 class="card-text text-title">What's on your mind?</h5>
                </div>
            </div>

            <?php
                $count = 0;
                $countUnrateForm = 0;
                $allCount = 0;

                foreach ($posts as $post) {
                    $tokenName = $this->security->getTokenKey();
                    $tokenValue = $this->security->getToken();
                    $post_desc = $post->description();
                    $post_rate = $post->averageRating();
                    $post_id = $post->id()->id();
                    $post_img = $this->url->get('files/' . $post->file());
                    $post_title = $post->title();
                    $post_created_at  = $post->created_at();
                    $is_rated = $post->is_rated();

                    echo "
                    <div class='card mt-2'>
                        <div class='card-body'>
                            <div style='display : none;' class='id_holder'>$post_id</div>
                            <div class='my-card-header'>
                                <p class='card-text text-right'><small class='text-muted'>$post_created_at</small></p> 
                            </div>
                            
                            <h5 class='card-title title text-title'>$post_title</h5>
                            <img src='$post_img' class='my-card-img' alt='post-img'>
                        
                            <p style='margin-top : 6px;' class='card-text desc text-content text-justify'>$post_desc</p>
                            
                            
                            <div class='my-card-footer row align-items-center'>
        
                                <div class='action d-flex align-items-center col-auto'>
                                    <div class='action-item'>
                                
                                        <a href='#' onclick='openEditModel($allCount)'><small style='color : blue;'>EDIT</small></a>
        
                                    </div>
                                    <div class='action-item'>
                                        <a href='/post/index/delete/$post_id' ><small style='color : red;'>DELETE</small></a>
                                    </div>
                                </div>
        
                                <div class='rating-view col-auto ml-auto d-flex flex-row-reverse align-items-center'>

                            ";

                            if($is_rated){
                                echo "

                                    <small class='clickable' onclick='submitUnrateForm($countUnrateForm)'>UNRATED</small>
                                    
                                   
                                    <form class='unrate-form' action='/post/index/unrate' method='post'>
                                        <input type='hidden' name='post_id' value='$post_id' />
                                    <form>


                                ";

                                $countUnrateForm++;
                            }else{
                                echo "
                                    <small class='clickable' onclick='openRateForm($count)'>RATE POST</small>
                                ";
                            }

                        

                            echo"
                                    <form method='post' action='/post/index/rating' class='rating-form'>
                                        <input placeholder='Rate 1 - 5' step='1' max='5' type='number' name='rating' class='form-control rating-input' ></input>
                                      
                                        <input id='ed-postid' type='hidden' name='post_id' value='$post_id' />

                                        <div class='row no-gutters justify-content-center'>
                                            <button style='margin : 3px' class='btn btn-primary btn-sm col-sm-5' type='submit'>Rate</button>
                                            <button style='margin : 3px' class='btn btn-danger btn-sm col-sm-5' type='button' onclick='closeRateForm($count)' >Cancel</button>
                                        </div>
                                        
                                        
                                    </form>

                                    <div class='divider-horizontal'></div>
                                    <small class='total-rate'>$post_rate</small>
                                    <span class='material-icons' style='color : #FEC706;'>
                                        grade
                                    </span>
                            
                                </div>
        
                            </div>
        
                        </div>
                    </div>
                    ";

                    if($is_rated == false)
                    {
                        $count++;
                    }

                    $allCount++;
    
                } 


            ?>

                                
            <div class="size-box" style="height : 50px;"><div>

        </div>
    </div>

</div>

<div class="backdrop" onclick="closeAllModel()"> </div>

<div class="model-container">
  
    <div class="model center">
        <form class="post-form" action="/post/index/create" method="post" enctype="multipart/form-data">
            
            <div class="form-group">
                <label for="exampleFormControlInput1">Title</label>
                <input name="title" type="text" class="form-control" id="exampleFormControlInput1" placeholder="Title">
            </div>

            <div class="form-group">
                <label for="exampleFormControlTextarea1">Description</label>
                <textarea name="description" class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
            </div>

            <input type="file" name="file" placeholder="file"><br>


            <input type='hidden' name='<?php echo $this->security->getTokenKey() ?>'
                value='<?php echo $this->security->getToken() ?>'/>

            <br>
            
            <button class="btn btn-primary" type="submit">submit</button>

        </form>
    </div>
   
</div>  


<div class="model-edform-container">
  
    <div class="model center">
        <form class="post-form" action="/post/index/edit" method="post" enctype="multipart/form-data">
            
            <div class="form-group">
                <label for="exampleFormControlInput1">Title</label>
                <input name="title" type="text" class="form-control" id="ed-title" placeholder="Title">
            </div>

            <div class="form-group">
                <label for="exampleFormControlTextarea1">Description</label>
                <textarea name="description" class="form-control" id="ed-desc" rows="3"></textarea>
            </div>

            <input type="file" name="file" placeholder="file"><br>
            <input id="ed-postidw" type='hidden' name='post_id' />


            <input type='hidden' name='<?php echo $this->security->getTokenKey() ?>'
                value='<?php echo $this->security->getToken() ?>'/>

            <br>
            
            <button class="btn btn-primary" type="submit">submit</button>

        </form>
    </div>
   
</div>  

<!-- <form class='unrate-form' action='/post/index/unrate' method='post'>
    <input type='hidden' name='post_id' value='$post_id' />
    <button class='btn btn-warning btn-sm' type='submit' id='unrate-button'>UNRATED</button>
<form> -->

