<div class="container-fluid">

    <div class="row justify-content-center">

        <div class="col-sm-8">
            <div class="card mt-5">
                <div class="card-body clickable" onclick="openModel()">
                    <h5 class="card-text text-title">Create new Subredlite</h5>
                </div>
            </div>

            <?php

                foreach ($subRedlites as $subRedlite) {

                    $tokenName = $this->security->getTokenKey();
                    $tokenValue = $this->security->getToken();
                    $subredliteId = $subRedlite->id;
                    $subredliteName = $subRedlite->name;
                    $subredliteDesc = $subRedlite->description;
                    $subredliteOwner = $subRedlite->owner_id;

                    echo "
                        <a href='/redlite/subredlite/$subredliteId'>
                        <div class='card mt-2'>
                            <div class='card-body'>
                                <h5 class='card-title title text-title'>$subredliteName</h5>
                                <p style='margin-top : 6px;' class='card-text desc text-content text-justify'>$subredliteDesc</p>
                            
                                <div class='my-card-footer row align-items-center'>
                                    <div class='action d-flex align-items-center col-auto'>

                    ";

                    if ($userId == $subredliteOwner) {
                        echo "
                                        <div class='action-item'>
                                            <a href='#' onclick='openEditModel($subredliteId)'><small style='color : blue;'>EDIT</small></a>
                                        </div>

                                        <div class='action-item'>
                                            <a href='/redlite/subredlite/index/delete/$subredliteId' ><small style='color: red;'>DELETE</small></a>
                                        </div>
                        ";
                    }

                    echo "
                                    </div>
                                </div>
                            </div>
                        </div>
                        </a>
                    ";
                }
            ?>
            
            <div class="size-box" style="height : 50px;"><div>

        </div>
    </div>
</div>

<div class="backdrop" onclick="closeAllModel()"> </div>

<div class="model-container">
  
    <div class="model center">
        <form class="post-form" action="/redlite/subredlite/index/create" method="post" enctype="multipart/form-data">
            
            <div class="form-group">
                <label for="nameFormInput">Name</label>
                <input name="name" type="text" class="form-control" id="nameFormInput" placeholder="Name">
            </div>

            <div class="form-group">
                <label for="descFormInput">Description</label>
                <textarea name="description" class="form-control" id="descFormInput" rows="3"></textarea>
            </div>

            <input type='hidden' name='<?php echo $this->security->getTokenKey() ?>'
                value='<?php echo $this->security->getToken() ?>'/>

            <br>
            
            <button class="btn btn-primary" type="submit">Create</button>

        </form>
    </div>
</div>  


<div class="model-edform-container">
    <div class="model center">
        <form class="post-form" action="/redlite/subredlite/index/delete/$subredliteId" method="post" enctype="multipart/form-data">
            
            <div class="form-group">
                <label for="exampleFormControlInput1">Title</label>
                <input name="title" type="text" class="form-control" id="ed-title" placeholder="Title">
            </div>

            <div class="form-group">
                <label for="exampleFormControlTextarea1">Description</label>
                <textarea name="description" class="form-control" id="ed-desc" rows="3"></textarea>
            </div>

            <input id="ed-postidw" type='hidden' name='post_id' />

            <input type='hidden' name='<?php echo $this->security->getTokenKey() ?>'
                value='<?php echo $this->security->getToken() ?>'/>
            
            <button class="btn btn-primary" type="submit">submit</button>

        </form>
    </div>
</div>  
