
<div class="w3layouts-main"> 
	<div class="bg-layer">
		<h1>Redlite Login</h1>
		<div class="header-main">
			<div class="main-icon">
				<span class="fa fa-eercast"></span>
			</div>
			<div class="header-left-bottom">
				<form action="/user/index/login" method="post">
					<div class="icon1">
						<span class="fa fa-envelope"></span>
						<!-- <input type="email" placeholder="Email Address" required=""/> -->
                        <?php echo $loginForm->render('email'); ?>
					</div>
					<div class="icon1">
						<span class="fa fa-lock"></span>
						<!-- <input type="password" placeholder="Password" required=""/> -->
                        <?php echo $loginForm->render('password'); ?>
					</div>
					<div class="login-check">
						 <label class="checkbox"><input type="checkbox" name="checkbox" checked=""><i> </i> Keep me logged in</label>
					</div>
					<div class="bottom">
						<button class="btn">Log In</button>
					</div>
					<div class="links">
						<p><a href="#">Forgot Password?</a></p>
						<p class="right"><a href="/user/index/signup">New User? Register</a></p>
						<div class="clear"></div>
					</div>
				</form>	
			</div>
			<div class="social">
				<ul>
					<li>or login using : </li>
					<li><a href="#" class="facebook"><span class="fa fa-facebook"></span></a></li>
					<li><a href="#" class="twitter"><span class="fa fa-twitter"></span></a></li>
					<li><a href="#" class="google"><span class="fa fa-google-plus"></span></a></li>
				</ul>
			</div>
		</div>
		
		
		<div class="copyright">
			<p>Privacy policy | Term of Use</p>
		</div>
		
	</div>
</div>