
<!DOCTYPE html>
<html>
<head>
<title>Redlite</title>

<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="keywords" content="Slide Login Form template Responsive, Login form web template, Flat Pricing tables, Flat Drop downs Sign up Web Templates, Flat Web Templates, Login sign up Responsive web template, SmartPhone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />

	 <script>
        addEventListener("load", function () {
            setTimeout(hideURLbar, 0);
        }, false);

        function hideURLbar() {
            window.scrollTo(0, 1);
        }
    </script>


	<link href="<?php echo $this->url->get('css/login_styles.css')?>" rel="stylesheet" type="text/css" media="all" />
	<link href="<?php echo $this->url->get('css/font-awesome.min.css')?>" rel="stylesheet" type="text/css" media="all" />


	<link href="//fonts.googleapis.com/css?family=Hind:300,400,500,600,700" rel="stylesheet">

</head>
<body>

<?php echo $this->getContent(); ?>

</body>
</html>


